# Generated by Django 5.2.8 on 2026-05-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_registration_face_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='event_qr_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
