# Generated by Django 5.2.8 on 2026-05-19 03:35

import uuid
from django.db import migrations


def backfill_tokens(apps, schema_editor):
    """Extract tokens from legacy URL fields and populate the new token columns."""
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        changed = False

        # registration_link → registration_token
        if not event.registration_token and event.registration_link:
            token = event.registration_link.rstrip('/').rsplit('/', 1)[-1]
            event.registration_token = token
            changed = True
        elif not event.registration_token:
            event.registration_token = uuid.uuid4().hex
            changed = True

        # event_qr_code_url → event_qr_token
        if not event.event_qr_token and event.event_qr_code_url:
            token = event.event_qr_code_url.rstrip('/').rsplit('/', 1)[-1]
            event.event_qr_token = token
            changed = True
        elif not event.event_qr_token:
            event.event_qr_token = uuid.uuid4().hex
            changed = True

        # attendance_qr_code_url → attendance_token
        if not event.attendance_token and event.attendance_qr_code_url:
            token = event.attendance_qr_code_url.rstrip('/').rsplit('/', 1)[-1]
            event.attendance_token = token
            changed = True
        elif not event.attendance_token:
            event.attendance_token = uuid.uuid4().hex
            changed = True

        if changed:
            event.save(update_fields=[
                'registration_token', 'event_qr_token', 'attendance_token',
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_add_token_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_tokens, migrations.RunPython.noop),
    ]
